In [1]:
# astype
# between
# clip
# drop_duplicates
# isnull
# dropna
# fillna
# isin
# apply
# copy

In [2]:
import numpy as np
import pandas as pd

In [3]:
subs = pd.read_csv('subs.csv',)
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [4]:
vk = pd.read_csv('kohli_ipl.csv', index_col='match_no')

In [5]:
movies = pd.read_csv('bollywood.csv',index_col='movie',)
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [6]:
# astype
import sys
sys.getsizeof(vk)

3472

 - astype change data type and 
 - reduces the memory space

In [7]:
sys.getsizeof(vk.astype('int16'))

2182

## between 
 - 1 give your set of data of your range 
 -

In [8]:
vk_between = vk[vk['runs'].between(51, 99)]
vk_between

          runs
match_no
34          58
41          71
44          56
45          67
52          70
57          57
68          73
71          51
73          58
74          65
80          57
81          93
82          99
85          56
97          67
99          73
103         51
104         62
110         82
116         75
117         79
119         80
122         52
127         75
129         54
131         54
132         62
134         64
137         55
141         58
144         57
145         92
148         68
152         70
160         84
162         67
175         72
178         90
188         72
197         51
198         53
209         58
213         73

# clip
 - set value withing the range 100-200
 - 50 -->100
 - 269-->200

In [9]:
# clip
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [10]:
subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

# drop_duplicates
- delete as u like -- 1st or last

In [11]:
# drop_duplicates
temp = pd.Series([1,1,2,2,3,3,4,4])
temp

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [12]:
temp.drop_duplicates(keep='last')

1    1
3    2
5    3
7    4
dtype: int64

In [13]:
temp.duplicated().sum()

np.int64(4)

In [14]:
vk.duplicated().sum()

np.int64(137)

In [15]:
movies.drop_duplicates()

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Sssshhh...                            Tanishaa Mukerji
Rules: Pyaar Ka Superhit Formula                Tanuja
Right Here Right Now (film)                      Ankit
Talaash: The Hunt Begins...              Rakhee Gulzar
The Pink Mirror                        Edwin Fernandes

[566 rows x 1 columns]

In [16]:
temp = pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
temp

0     1.0
1     2.0
2     3.0
3     NaN
4     5.0
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [17]:
temp.size

10

In [18]:
temp.count()

np.int64(7)

In [19]:
# isnull
temp.isnull().sum()

np.int64(3)

In [20]:
# dropna
temp.dropna()

0     1.0
1     2.0
2     3.0
4     5.0
5     6.0
7     8.0
9    10.0
dtype: float64

In [21]:
# fillna
temp.fillna(temp.mean())

0     1.0
1     2.0
2     3.0
3     5.0
4     5.0
5     6.0
6     5.0
7     8.0
8     5.0
9    10.0
dtype: float64

In [22]:
# isin
vk[(vk == 49) | (vk == 99)]

          runs
match_no
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
...        ...
211        NaN
212        NaN
213        NaN
214        NaN
215        NaN

[215 rows x 1 columns]

In [23]:
vk[vk.isin([49,99])]

          runs
match_no
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
...        ...
211        NaN
212        NaN
213        NaN
214        NaN
215        NaN

[215 rows x 1 columns]

In [24]:
# apply
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [25]:
movies.apply(lambda x:x.split()[0].upper())

AttributeError: 'Series' object has no attribute 'split'

In [ ]:
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
subs.apply(lambda x:'good day' if x > subs.mean() else 'bad day')

0       bad day
1       bad day
2       bad day
3       bad day
4       bad day
         ...
360    good day
361    good day
362    good day
363    good day
364    good day
Name: Subscribers gained, Length: 365, dtype: object

In [ ]:
subs.mean()

135.64383561643837

In [ ]:
# copy

In [ ]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [ ]:
new = vk.head()

In [ ]:
new

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [ ]:
new[1] = 1

In [ ]:
new = vk.head().copy()

In [ ]:
new[1] = 100

In [ ]:
new

match_no
1    100
2     23
3     13
4     12
5      1
Name: runs, dtype: int64

In [ ]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64